bankingsystem/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from accounts.views import (login_view,
                            register_view,
                            logout_view
                            )

from core.views import home, about

urlpatterns = [
    # admin
    url(r'^admin/', admin.site.urls),
    # Accounts
    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
    # core
    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
    # transactions
    url(r'^', include('transactions.urls', namespace='transactions')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

transactions/urls.py
from django.conf.urls import url

from .views import diposit_view, withdrawal_view, transfer_view

urlpatterns = [
    # url(r'^$', home_view, name='home'),
    url(r'^deposit/$', diposit_view, name='deposit'),
    url(r'^withdrawal/$', withdrawal_view, name='withdrawal'),
    url(r'^transfer/$', transfer_view, name='transfer'),  
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.db.models import Sum
from django.shortcuts import render
from django.db.models import Q
from django.http import JsonResponse

import requests

from transactions.models import Diposit, Withdrawal, Interest, Transfer


def home(request):
    if not request.user.is_authenticated:
        return render(request, "core/home.html", {})
    else:
        user = request.user
        transfers = Transfer.objects.filter(Q(sender=str(user)) | Q(receiver=str(user)))
        deposit = Diposit.objects.filter(user=user)
        deposit_sum = deposit.aggregate(Sum('amount'))['amount__sum']
        withdrawal = Withdrawal.objects.filter(user=user)
        withdrawal_sum = withdrawal.aggregate(Sum('amount'))['amount__sum']
        interest = Interest.objects.filter(user=user)
        interest_sum = interest.aggregate(Sum('amount'))['amount__sum']

        if request.method == 'POST':
            currency = request.POST.get('selectedCurrency', 'error')
            curreArrat = currency.split(' ')
            r = requests.get('https://www.divipay.com/secure/currency/'+curreArrat[0]+'/')
            jsonResponseCurr = r.json()
            stringResult = float(user.balance) * float(jsonResponseCurr['rate'])

            return JsonResponse({'newCurrency':stringResult, 'sign': curreArrat[0]})


        context = {
                    "user": user,
                    "transfer": transfers,
                    "deposit": deposit,
                    "deposit_sum": deposit_sum,
                    "withdrawal": withdrawal,
                    "withdrawal_sum": withdrawal_sum,
                    "interest": interest,
                    "interest_sum": interest_sum,
                  }

        return render(request, "core/transactions.html", context)


def about(request):
    return render(request, "core/about.html", {})

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %} About | {{ block.super }}{% endblock title %}

{% block content %}

<h1>About US</h1>
<hr>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Why do we use it?</p>

<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
</p>


<p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>

{% endblock content %}

core/templates/core/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %} Banking System {% endblock title %}</title>

    <!-- Bootstrap -->
        <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}'>
        <link rel="stylesheet" href='{% static "css/bootstrap-theme.min.css" %}'>
  </head>

  <body>
{% include "core/navbar.html" %}

<div class="container" style="padding-top: 60px;">
{% block content %}

{% endblock content %}
</div>
{% include "core/footer.html" %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}" ></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>
        <script type="text/javascript" src="{% static 'js/main.js' %}" ></script>
  </body>
</html>

core/templates/core/footer.html
<hr>
<footer class="footer navbar-fixed">
    <!--Footer Links-->
    <div class="container-fluid">
        <div class="row">
            <!--First column-->
            <div class="col-md-6">
                <h4 class="title"><b>Footer Content</b></h4>
                <p>Here you can use rows and columns here to organize your footer content.</p>
            </div>
            <!--/.First column-->
            <!--Second column-->
            <div class="col-md-6">
                <h5 class="title"><b>Links</b></h5>

                <a href="{% url 'home' %}">Home </a>|
                <a href="{% url 'about' %}">About Us</a> |&nbsp;


            </div>
            <!--/.Second column-->
        </div>
    </div>
    <!--/.Footer Links-->
    <!--Copyright-->
    <div class="footer-copyright">
        <div class="container-fluid">
            © 2017 Copyright: <a href="http://127.0.0.1:8000/"> Divipay</a>
        </div>
    </div>
    <!--/.Copyright-->
</footer>
<br>

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %} {{ block.super }}{% endblock title %}

{% block content %}
<div class="container" style="padding-top: 50px;">
<div class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Banking System</h1>
        <hr>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
        <p>
          <a class="btn btn-primary btn-md" href="{% url 'login' %}" role="button">Load Account Details</a>
          <a class="btn btn-success btn-md" href="{% url 'register' %}" role="button">Create a Bank Account</a>
        </p>
      </div>
</div>
</div>

{% endblock content %}

core/templates/core/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

core/templates/core/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}" style="padding-left: 30px;">Banking System</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'home' %}">Home </a></li>
        <li><a href="{% url 'transactions:deposit' %}">Deposit</a></li>
        <li><a href="{% url 'transactions:withdrawal' %}">Withdraw</a></li>
        <li><a href="{% url 'transactions:transfer' %}">Transfer</a></li>
        <li><a href="{% url 'about' %}">About Us</a></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right" style="padding-right: 30px;">
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'login' %}">Load Account Details</a></li>
        <li><a href="{% url 'register' %}">Create an Account</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

core/templates/core/transactions.html
{% extends 'core/base.html' %}

{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}

    <div class="page-header">
      <h1 class="text-center"><b>Banking System</b><br><small>ABC Bank Ltd.</small></h1>
    </div>
    
<div class="row">

  <div class="col-xs-12 col-md-8 text-left">
    <h4><b>Account Name: </b>{{ user.full_name }}</h4>
    <h4><b>Date of Birth: </b>{{ user.birth_date }}</h4>
    <h4><b>Gender: </b>{{ user.gender }}</h4>
    <h4><b>Contact No: </b>{{ user.contact_no }}</h4>
    <h4><b>Email Address: </b>{{ user.email }}</h4>
    <h4><b>Address: </b>{{ user.Address }}</h4>
    <h4><b>Location: </b>{{ user.city }}, {{ user.country }}</h4>
    <h4><b>Occupation: </b>{{ user.occupation }}</h4>
  </div>
  <div class="col-xs-6 col-md-4 text-left">
    <h4><b>Account Created: </b>{{ user.date_joined|date:'d-m-Y' }}</h4>
    <h4><b>Account No: </b>{{ user.account_no }}</h4><br><br>
    <div class="well">
    <h4 class="card"><b>Account Balance: $</b><span id="balanceCur">{{ user.balance }} AUD</span></h4>
    <a class="btn btn-success" href="{% url 'transactions:deposit' %}">Deposit</a>
    <a class="btn btn-info" href="{% url 'transactions:transfer' %}">Transfer</a>
    <a class="btn btn-danger" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
    </div>
  </div>
  <div class="col-xs-6 col-md-4 text-left">  
    <div class="form-group">
      <select class="form-control" id="currency">
        <option>AED United Arab Emirates Dirham</option>
        <option>AFN Afghanistan Afghani</option>
        <option>ALL Albania Lek</option>
        <option>AMD Armenia Dram</option>
        <option>ANG Netherlands Antilles Guilder</option>
        <option>AOA Angola Kwanza</option>
        <option>ARS Argentina Peso</option>
        <option>AUD Australia Dollar</option>
        <option>AWG Aruba Guilder</option>
        <option>AZN Azerbaijan Manat</option>
        <option>BAM Bosnia and Herzegovina Convertible Marka</option>
        <option>BBD Barbados Dollar</option>
        <option>BDT Bangladesh Taka</option>
        <option>BGN Bulgaria Lev</option>
        <option>BHD Bahrain Dinar</option>
        <option>BIF Burundi Franc</option>
        <option>BMD Bermuda Dollar</option>
        <option>BND Brunei Darussalam Dollar</option>
        <option>BOB Bolivia Bolíviano</option>
        <option>BRL Brazil Real</option>
        <option>BSD Bahamas Dollar</option>
        <option>BTN Bhutan Ngultrum</option>
        <option>BWP Botswana Pula</option>
        <option>BYN Belarus Ruble</option>
        <option>BZD Belize Dollar</option>
        <option>CAD Canada Dollar</option>
        <option>CDF Congo/Kinshasa Franc</option>
        <option>CHF Switzerland Franc</option>
        <option>CLP Chile Peso</option>
        <option>CNY China Yuan Renminbi</option>
        <option>COP Colombia Peso</option>
        <option>CRC Costa Rica Colon</option>
        <option>CUC Cuba Convertible Peso</option>
        <option>CUP Cuba Peso</option>
        <option>CVE Cape Verde Escudo</option>
        <option>CZK Czech Republic Koruna</option>
        <option>DJF Djibouti Franc</option>
        <option>DKK Denmark Krone</option>
        <option>DOP Dominican Republic Peso</option>
        <option>DZD Algeria Dinar</option>
        <option>EGP Egypt Pound</option>
        <option>ERN Eritrea Nakfa</option>
        <option>ETB Ethiopia Birr</option>
        <option>EUR Euro Member Countries</option>
        <option>FJD Fiji Dollar</option>
        <option>FKP Falkland Islands (Malvinas) Pound</option>
        <option>GBP United Kingdom Pound</option>
        <option>GEL Georgia Lari</option>
        <option>GGP Guernsey Pound</option>
        <option>GHS Ghana Cedi</option>
        <option>GIP Gibraltar Pound</option>
        <option>GMD Gambia Dalasi</option>
        <option>GNF Guinea Franc</option>
        <option>GTQ Guatemala Quetzal</option>
        <option>GYD Guyana Dollar</option>
        <option>HKD Hong Kong Dollar</option>
        <option>HNL Honduras Lempira</option>
        <option>HRK Croatia Kuna</option>
        <option>HTG Haiti Gourde</option>
        <option>HUF Hungary Forint</option>
        <option>IDR Indonesia Rupiah</option>
        <option>ILS Israel Shekel</option>
        <option>IMP Isle of Man Pound</option>
        <option>INR India Rupee</option>
        <option>IQD Iraq Dinar</option>
        <option>IRR Iran Rial</option>
        <option>ISK Iceland Krona</option>
        <option>JEP Jersey Pound</option>
        <option>JMD Jamaica Dollar</option>
        <option>JOD Jordan Dinar</option>
        <option>JPY Japan Yen</option>
        <option>KES Kenya Shilling</option>
        <option>KGS Kyrgyzstan Som</option>
        <option>KHR Cambodia Riel</option>
        <option>KMF Comorian Franc</option>
        <option>KPW Korea (North) Won</option>
        <option>KRW Korea (South) Won</option>
        <option>KWD Kuwait Dinar</option>
        <option>KYD Cayman Islands Dollar</option>
        <option>KZT Kazakhstan Tenge</option>
        <option>LAK Laos Kip</option>
        <option>LBP Lebanon Pound</option>
        <option>LKR Sri Lanka Rupee</option>
        <option>LRD Liberia Dollar</option>
        <option>LSL Lesotho Loti</option>
        <option>LYD Libya Dinar</option>
        <option>MAD Morocco Dirham</option>
        <option>MDL Moldova Leu</option>
        <option>MGA Madagascar Ariary</option>
        <option>MKD Macedonia Denar</option>
        <option>MMK Myanmar (Burma) Kyat</option>
        <option>MNT Mongolia Tughrik</option>
        <option>MOP Macau Pataca</option>
        <option>MRU Mauritania Ouguiya</option>
        <option>MUR Mauritius Rupee</option>
        <option>MVR Maldives (Maldive Islands) Rufiyaa</option>
        <option>MWK Malawi Kwacha</option>
        <option>MXN Mexico Peso</option>
        <option>MYR Malaysia Ringgit</option>
        <option>MZN Mozambique Metical</option>
        <option>NAD Namibia Dollar</option>
        <option>NGN Nigeria Naira</option>
        <option>NIO Nicaragua Cordoba</option>
        <option>NOK Norway Krone</option>
        <option>NPR Nepal Rupee</option>
        <option>NZD New Zealand Dollar</option>
        <option>OMR Oman Rial</option>
        <option>PAB Panama Balboa</option>
        <option>PEN Peru Sol</option>
        <option>PGK Papua New Guinea Kina</option>
        <option>PHP Philippines Piso</option>
        <option>PKR Pakistan Rupee</option>
        <option>PLN Poland Zloty</option>
        <option>PYG Paraguay Guarani</option>
        <option>QAR Qatar Riyal</option>
        <option>RON Romania Leu</option>
        <option>RSD Serbia Dinar</option>
        <option>RUB Russia Ruble</option>
        <option>RWF Rwanda Franc</option>
        <option>SAR Saudi Arabia Riyal</option>
        <option>SBD Solomon Islands Dollar</option>
        <option>SCR Seychelles Rupee</option>
        <option>SDG Sudan Pound</option>
        <option>SEK Sweden Krona</option>
        <option>SGD Singapore Dollar</option>
        <option>SHP Saint Helena Pound</option>
        <option>SLL Sierra Leone Leone</option>
        <option>SOS Somalia Shilling</option>
        <option>SRD Suriname Dollar</option>
        <option>STN São Tomé and Príncipe Dobra</option>
        <option>SVC El Salvador Colon</option>
        <option>SYP Syria Pound</option>
        <option>SZL Swaziland Lilangeni</option>
        <option>THB Thailand Baht</option>
        <option>TJS Tajikistan Somoni</option>
        <option>TMT Turkmenistan Manat</option>
        <option>TND Tunisia Dinar</option>
        <option>TOP Tonga Pa'anga</option>
        <option>TRY Turkey Lira</option>
        <option>TTD Trinidad and Tobago Dollar</option>
        <option>TVD Tuvalu Dollar</option>
        <option>TWD Taiwan New Dollar</option>
        <option>TZS Tanzania Shilling</option>
        <option>UAH Ukraine Hryvnia</option>
        <option>UGX Uganda Shilling</option>
        <option>USD United States Dollar</option>
        <option>UYU Uruguay Peso</option>
        <option>UZS Uzbekistan Som</option>
        <option>VEF Venezuela Bolívar</option>
        <option>VND Viet Nam Dong</option>
        <option>VUV Vanuatu Vatu</option>
        <option>WST Samoa Tala</option>
        <option>XAF Communauté Financière Africaine (BEAC) CFA Franc BEAC</option>
        <option>XCD East Caribbean Dollar</option>
        <option>XDR International Monetary Fund (IMF) Special Drawing Rights</option>
        <option>XOF Communauté Financière Africaine (BCEAO) Franc</option>
        <option>XPF Comptoirs Français du Pacifique (CFP) Franc</option>
        <option>YER Yemen Rial</option>
        <option>ZAR South Africa Rand</option>
        <option>ZMW Zambia Kwacha</option>
        <option>ZWD Zimbabwe Dollar</option>
      </select>
    </div>
  </div>
</div>

<hr>

  <div class="page-header">
  <h2 class="text-center"><b>Transaction Details</b></h2>
</div>

<h3>Deposit Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount ($)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in deposit %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Deposit</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ deposit_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>

<h3>Transfer Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Sender</th>
      <th>Receiver</th>
      <th>Amount in AUD</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in transfer %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>{{ obj.sender }}</td>
      <td>{{ obj.receiver }}</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}   
  </tbody>
</table>
<hr>


<h3>Withdrawal Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount ($)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in withdrawal %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Withdrawal</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ withdrawal_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>


<h3>Interest Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount ($)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in interest %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Interest</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ interest_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>
{% csrf_token %}
{% endblock content %}